config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'home/index'
  root :to => "splash#index"
  get "/category/", to: "category#index", as: "all_category"
  get "/category/show/:id", to: "category#show", as: "category_show"
  get "/category/new", to: "category#new", as: "new_category"
  post '/category/create', to: 'category#create', as: "create_category"
  get "/transaction/", to: "transaction#index", as: "all_transaction"
  get "/transaction/show/:id", to: "transaction#show", as: "transaction_show"
  get "/transaction/new", to: "transaction#new", as: "new_transaction"
  post '/transaction/create', to: 'transaction#create', as: "create_transaction"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_transacs, dependent: :delete_all
  has_many :transacs, through: :category_transacs
  validates :name, presence: true

  def amount
    result = 0
    transacs.each { |transac| result += transac.amount }
    result
  end
end

app/models/category_transac.rb
class CategoryTransac < ApplicationRecord
  belongs_to :category
  belongs_to :transac
end

app/models/transac.rb
class Transac < ApplicationRecord
  belongs_to :user
  has_many :category_transacs, dependent: :delete_all
  has_many :categories, through: :category_transacs
  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :category
  has_many :trans
  validates :fullname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    all_category_path
  end

  def after_sign_up_path_for(_resource)
    all_category_path
  end

  def after_sign_out_path_for(_resource_or_scope)
    user_session_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |u|
      u.permit(:email, :password)
    end
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:fullname, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:fullname, :email, :password_confirmation, :current_password)
    end
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :authenticate_user!
  def index
    @category = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new(params.require(:category).permit(:name, :icon, :user_id, :categories))
    respond_to do |format|
      if category.save
        format.html do
          flash[:success] = 'category saved successfully'
          redirect_to all_category_path
        end
      else
        flash.now[:error] = 'Error: category could not be saved'
        render :new, locals: { category: category }
      end
    end
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  before_action :authenticate_user!
  def index
    @transaction = Transac.find(params[:id])
  end

  def show
    @transaction = Transac.where(user: current_user)
  end

  def new
    @transaction = Transac.new
    @categories = Category.where(user: current_user)
  end

  def create
    transaction = Transac.new(params.require(:transac).permit(:name, :amount, :user_id))
    params[:categories].each do |key, _value|
      CategoryTransac.create(category: Category.find(key), transac: transaction)
    end
    respond_to do |format|
      if transaction.save
        format.html do
          flash[:success] = 'transaction saved successfully'
          redirect_to transaction_show_path(1)
        end
      else
        flash.now[:error] = 'Error: transaction could not be saved'
        render :new, locals: { transaction: transaction }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/category/index.html.erb
<%= render "shared/header" %>
<div class = "bg-light">
<div class ="bg-primary p-2  d-flex justify-content-end align-items-center">
  <p class ="mx-5 text_white">Most Recent</p>
   <p class ="text_white">Most ancent</p>
</div>
<% @category.each do |category| %>
<%= link_to transaction_show_path(category.id) do %>
  <div class="row border my-3 mx-2 p-3 bg-white">
     <div class="col-3">
       <img src=<%= category.icon %> alt="Category Icon" class="m-1 img-fluid rounded-1">
    </div>
    <div class="col-6">
      <p class="category-name"><%= category.name %></p>
      <span class="date"><%= category.created_at %></span>
    </div>
    <div class="col-3">
      <span class="amount">$<%= category.amount %></span>
    </div>
  </div>
   <% end %>
  <% end %>
  <div class="bottom-container position-fixed bottom-0 w-100">
  <div class="inner-bottom-container text-center">
    <%= link_to "NEW CATEGORY", new_category_path, class: "bottom-btn" %>
  </div>
</div>
  </div>

app/views/category/new.html.erb
<div class = "container bg-light">
<h6 class ="text-center m-3">New category</h6>
<%= form_with model: @category, url: create_category_path do |form| %>
  <%= form.text_field :name, placeholder: 'name', class: 'form-control mb-3' %>
  <%= form.text_field :icon, placeholder: 'icon', class: 'form-control mb-3' %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.submit "Submit", class: 'form-control btn btn-primary' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand text_white mx-3" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item">
          <%= button_to 'Sign out', destroy_user_session_path, :method => :delete,  class: "nav-link border-0 bg-primary" %>
        </li>
    </ul>
  </div>
</nav>

app/views/splash/index.html.erb
<div class="container border">
  <div class="row splachContainer">
  <div class = "d-flex flex-column justify-content-around">
    <h3  class ="p-2 text-center">Mustafa budget App</h3>
    <div class ="d-flex flex-column align-items-stretch align-items-lg-center">
    <%= link_to 'LOG IN', user_session_path,class:'my-3 btn btn-primary' %>
    <%= link_to 'SIGN UP', new_user_registration_path,class:'btn btn-outline-primary' %>
     </div>
    </div>
  </div>
</div>

app/views/transaction/index.html.erb
<% @transaction.each do |transaction| %>
  <div class="row border m-5 p-5">
     <div class="col-4">
            <h1><%= transaction.name %></h1>
     </div>
  </div>
  <% end %>

app/views/transaction/new.html.erb
<div class = "container bg-light">
<h6 class ="text-center m-3">New transaction</h6>
<%= form_with model: @transaction, url: create_transaction_path do |form| %>
  <%= form.text_field :name, placeholder: 'name', class: 'form-control mb-3' %>
  <%= form.number_field :amount, placeholder: 'amount', class: 'form-control mb-3' %>
   <% @categories.each do |category| %>
      <%= label_tag category.name %>
      <%= check_box_tag "categories[#{category.id}]", category.name %>
      <br />
    <% end %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.submit "Submit", class: 'form-control btn btn-primary' %>
<% end %>
</div>

app/views/transaction/show.html.erb
   <%= render "shared/header" %>
<div class = "bg-light">
<div class ="bg-primary p-2  d-flex justify-content-end align-items-center">
  <p class ="mx-5 text_white">Most Recent</p>
   <p class ="text_white">Most ancent</p>
</div>
<% @transaction.each do |transaction| %>
  <div class="row border my-3 mx-2 p-3 bg-white">
     <div class="col-3">
      <img src=<%= transaction.name %> alt="" class="m-1 img-fluid rounded-1">
    </div>
    <div class="col-6">
      <p class="category-name"><%= transaction.name %></p>
      <span class="date"><%= transaction.created_at %></span>
    </div>
    <div class="col-3">
      <span class="amount">$<%= transaction.amount %></span>
    </div>
  </div>
  <% end %>
  <div class="bottom-container position-fixed bottom-0 w-100">
  <div class="inner-bottom-container text-center">
    <%= link_to "NEW TRANSACTION", new_transaction_path, class: "bottom-btn" %>
  </div>
</div>
  </div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>



<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>